server:
  port: 4002
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    url: jdbc:mysql://192.168.7.33:3306/qyx_fund?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.taolue.baoxiao.fund.entity
 
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 5
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.taolue.baoxiao.fund.common.utils.FieldFillHandler
    
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    



